name: 'lcamtuf_download'
description: 'Browser Download Things'
category: 'Social Engineering'
authors: ['Your Name']
target:
  user_notify: false
  os: ['windows', 'linux', 'macos']
  browsers: ['ALL']
options:
  - name: 'malicious_file_uri'
    ui_label: 'Malicious File URL'
    description: 'Enter the file URL to force download in the victim browser.'
    type: 'textarea'
    width: '400px'
    height: '80px'
